project_id = "yexwaudgflncjpyfflll"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-user]
    verify_jwt = false
  [functions.send-birthday-emails]
    verify_jwt = false
  [functions.create-njangi-period]
    verify_jwt = false
